#!/usr/bin/env python3
"""Build one self-contained face page per character.

    python3 faces/build.py              # every character
    python3 faces/build.py chopper      # just one

A face is `renderer.js` -- the signal-face component exactly as authored, with
only its landmarks lifted into data -- wrapped in a shell, with the character's
portrait inlined as a data URI. Output goes to `native/Arisu/Face/<id>.html`,
which is a folder reference in the Xcode project, so a new character needs no
project edit: build it, and it is in the bundle.

Adding a character is two files here: `portraits/<id>.png` and `<id>.json`.
The JSON is the landmarks, as fractions of the frame:

    {"bw": 300, "bh": 314,
     "eyeL": [0.375, 0.470], "eyeR": [0.674, 0.468],
     "mouth": [0.512, 0.672],
     "eyeScale": 1.0, "mouthScale": 1.0, "jaw": 0.66}

Measure them off the artwork rather than guessing -- `grid.py` beside this file
prints a portrait with a coordinate grid over it for exactly that. Eyes and
mouth wrong by a few percent is a face that blinks beside its eye.

Two things the build does that are not obvious, both learned the hard way:

* The portrait is inlined, not loaded from beside the page. A file:// image
  taints the canvas, and `getImageData` on a tainted canvas throws -- which is
  the whole of how this renderer works. A data: URI does not taint it.

* The portrait is flattened onto black if it has any transparency. A PNG's
  fully transparent pixels still carry colour, `getImageData` hands it back
  unpremultiplied, and the renderer lights that junk as though it were a
  subject. Arisu's first portrait came out as a bright field of noise with a
  head-shaped hole in it.
"""
import base64
import io
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "native" / "Arisu" / "Face"

HEAD = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover, user-scalable=no">
<title>%(name)s</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  html, body { height: 100%%; background: transparent; overflow: hidden;
               -webkit-user-select: none; user-select: none;
               -webkit-touch-callout: none; }
  #stage { position: fixed; inset: 0; background: transparent; }
  #face  { position: absolute; inset: 0; width: 100%%; height: 100%%; display: block; }
  #src   { position: absolute; width: 1px; height: 1px; opacity: 0; pointer-events: none; }
</style>
</head>
<body>
<div id="stage">
  <img id="src" src="%(portrait)s" alt="" aria-hidden="true">
  <canvas id="face"></canvas>
</div>
<script>
/* ---------------------------------------------------------------------------
 * %(name)s's face. GENERATED by faces/build.py -- edit faces/, not this.
 *
 * The renderer below is the signal-face component as authored, so a newer one
 * drops in whole rather than being merged by hand. Only its face landmarks
 * were lifted into data, because every character sits differently in frame.
 *
 * It was written as a React component but only ever used React to hold eight
 * refs, so the shim below is the whole of React that it needs. The debug
 * chrome it can drive -- a state label, an amplitude bar, a status dot, a
 * settings panel, a mic button -- has no place on a desk pet, so those five
 * refs get detached elements. Nothing is appended and the writes fall away.
 *
 * Swift drives it through `window.avatar`: `setState` for the phase and
 * `setAmplitude` for the voice.
 * ------------------------------------------------------------------------- */

window.CHARACTER_FACE = %(config)s;

const React = { createRef: () => ({ current: null }) };
class DCLogic { constructor(p) { this.props = p || {}; } }

"""

TAIL = """

/* ---- mount ------------------------------------------------------------- */

const stub = () => document.createElement('div');

const face = new Component({
  palette: 'Neon Bloom',
  renderMode: 'Hologram',
  lineSpacing: 3.1,
  bloom: 1.0,
  aliveness: 0.8,
  // 60 on a pet that runs all day is a waste of a battery; the effect is
  // bloom-soft and interlaced, so half of it reads the same across the room.
  fpsCap: 30
});

face.canvasRef.current = document.getElementById('face');
face.stageRef.current  = document.getElementById('stage');
face.srcRef.current    = document.getElementById('src');
face.panelRef.current  = stub();
face.stateRef.current  = stub();
face.ampRef.current    = stub();
face.dotRef.current    = stub();
face.micRef.current    = stub();

face.componentDidMount();

// applyChrome paints the stage and the document a solid colour, which would put
// an opaque plate in front of the gradient SwiftUI draws behind this view. The
// hologram raster already writes alpha 0 wherever there is no signal, so this
// is the only thing standing between the character and that background.
const paint = face.applyChrome.bind(face);
face.applyChrome = (mode) => {
  paint(mode);
  document.body.style.background = 'transparent';
  document.documentElement.style.background = 'transparent';
  if (face.stageRef.current) face.stageRef.current.style.background = 'transparent';
};
face.applyChrome(face.props.renderMode);

// The renderer sizes its backing store once at mount and then only on a window
// resize event. In a browser the window already has a size by then; in a web
// view it does not -- the first layout arrives after the page loads, fires no
// resize event, and the canvas stays at the 1x1 it measured. That is a face
// running perfectly and drawing nothing, which is exactly what it looked like.
// Watch the stage instead of the window.
if (window.ResizeObserver) {
  let w = 0, h = 0;
  new ResizeObserver((entries) => {
    const r = entries[0].contentRect;
    if (Math.round(r.width) === w && Math.round(r.height) === h) return;
    w = Math.round(r.width); h = Math.round(r.height);
    if (w > 0 && h > 0) face.resize();
  }).observe(face.stageRef.current);
}

const src = face.srcRef.current;
const ready = () => { window.arisuReady = true; };
if (src.complete && src.naturalWidth) ready(); else src.addEventListener('load', ready);

window.arisuFace = face;
</script>
</body>
</html>
"""


def portrait_uri(path):
    """The portrait as a data URI, flattened onto black if it has any alpha."""
    from PIL import Image
    im = Image.open(path)
    if im.mode in ("RGBA", "LA", "P"):
        im = im.convert("RGBA")
        _, _, _, alpha = im.split()
        if alpha.getextrema()[0] < 255:
            flat = Image.new("RGB", im.size, (0, 0, 0))
            flat.paste(im, mask=alpha)
            im = flat
        else:
            im = im.convert("RGB")
    buf = io.BytesIO()
    im.convert("RGB").save(buf, format="PNG", optimize=True)
    return ("data:image/png;base64,"
            + base64.b64encode(buf.getvalue()).decode("ascii"), im.size)


def build(cid, renderer):
    config_path = HERE / (cid + ".json")
    if not config_path.exists():
        raise SystemExit("no faces/%s.json -- see the docstring" % cid)
    config = json.loads(config_path.read_text())

    portraits = [p for p in (HERE / "portraits").glob(cid + ".*")
                 if p.suffix.lower() in (".png", ".jpg", ".jpeg", ".webp")]
    if not portraits:
        raise SystemExit("no faces/portraits/%s.* -- the face needs a picture" % cid)
    uri, size = portrait_uri(portraits[0])

    # The buffer keeps the portrait's aspect ratio, so a face is never squashed
    # by the frame it is sampled into. Width is fixed: it is a cost, not a look.
    config.setdefault("bw", 300)
    config.setdefault("bh", max(1, round(config["bw"] * size[1] / size[0])))

    name = config.get("name", cid.capitalize())
    page = (HEAD % {"name": name, "portrait": uri,
                    "config": json.dumps(config, indent=2)}
            + renderer + TAIL)
    OUT.mkdir(parents=True, exist_ok=True)
    out = OUT / (cid + ".html")
    out.write_text(page, encoding="utf-8")
    print("%-10s %s  (%dx%d portrait, %d KB page)"
          % (cid, out.relative_to(HERE.parent), size[0], size[1],
             len(page.encode()) // 1024))


def main(argv):
    renderer = (HERE / "renderer.js").read_text(encoding="utf-8")
    ids = argv[1:] or sorted(p.stem for p in HERE.glob("*.json"))
    if not ids:
        raise SystemExit("no characters in faces/")
    for cid in ids:
        build(cid, renderer)


if __name__ == "__main__":
    main(sys.argv)
